project_id = "gvfptmjluxpngfjendbi"

[functions.create-payment-intent]
verify_jwt = false

[functions.get-inventory-status]
verify_jwt = false

[functions.sendcloud-webhook]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.meta-capi-relay]
verify_jwt = false
